[tool.poetry]
name = "flow360-betdisk"
version = "0.1.8"
description = ""
authors = ["An Li <kidylee@gmail.com>"]
packages= [
    { include = "BETDisk" },
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

