[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pandas_plus"
version = "0.0.4"
authors = [
  { name="Madhukar Kumar Jha", email="madhukar.k.jha@gmail.com" },
]
description = "A package to enhance common day to day tasks in the life of a data scientist"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/maddytae/project_pandas_plus"
"Bug Tracker" = "https://github.com/maddytae/project_pandas_plus/issues"