[tool.black]
line-length = 120
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \
    | _build
    | buck-out
    | build
    | dist
    | venv
    | node_modules
  )/
)
'''

[[tool.poetry.source]]
name = "properly"
url = "https://pypi.fury.io/properly/"

[tool.poetry]
name = "properly-util-python"
version = "0.1.0"
description = "Legacy Python utilities"
authors = ["Properly Engineering <itops_general@properly.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.*"
boto3 = "1.21.21"
botocore = "1.24.21"
aioboto3 = "9.5.0"
certifi = "2018.4.16"
chardet = "3.0.4"
docutils = "0.14"
Flask = ">=1.1.4"
googlemaps = "3.0.2"
idna = ">=2.6"
jmespath = "0.9.3"
pkginfo = "1.4.2"
pygeohash = "1.2.0"
python-dateutil = "2.7.3"
requests = "2.28.0"
requests-toolbelt = "0.8.0"
s3transfer = "0.5.0"
Shapely = ">=1.7a1"
six = ">=1.11.0"
tqdm = "4.23.4"
twine = ">=1.11.0"
urllib3 = "1.25.4"
pytest = "5.2.1"
orjson = ">3,<3.6"
deprecation = "2.1.0"
dynamodb-json = "1.3"
markupsafe = "2.0.1" # pinned because updating Flask to 1.1.4 uses a version of jinja where this breaks


[tool.poetry.group.dev.dependencies]
pytest = "5.2.1"
pytest-asyncio = "0.10.0"
black = "22.10.0"
invoke = ">=1.7.3"
isort = "^5.10.1"
ssort = "^0.11.6"
properly-util-python-private = "2.3.*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
