[tool.poetry]
name = "unhidden"
version = "0.5.0"
description = ""
authors = ["Burak Akkaya <akkaya.burak@outlook.com>"]
readme = "README.md"

[tool.poetry.scripts]
unhidden = "unhidden.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.6.1"
pandas = "^1.5.0"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
